export const LOAD_CODEFILES = 'LOAD_CODEFILES';

export const CODE_UPDATE = 'CODE_UPDATE';
export const CODE_RUN_START = 'CODE_RUN_START';
export const CODE_RUN_FINISH = 'CODE_RUN_FINISH';
export const CODE_RUN_CANCEL = 'CODE_RUN_CANCEL';
export const CHANGE_FOCUS = 'CHANGE_FOCUS';
